[phases.setup]
nixPkgs = ["nodejs_20", "python311", "python311Packages.pip", "ffmpeg"]

[phases.install]
cmds = [
  "ln -sf $(which python3) /usr/local/bin/python",
  "npm i",
  "python3 -m pip install yt-dlp"
]

[start]
cmd = "node index.js"
